nome = str(input("Qual é seu nome completo? ")).strip()
print(' ------ Analisando seu nome ----------')
print('Seu nome em letras maiúsculas é {}'.format(nome.upper()))
print('Seu nome em letras minúsculas é {}'.format(nome.lower()))
print('Seu nome tem ao todo {} letras'.format(len(nome) - nome.count(' ')))
#print('Seu primeito nome tem {} letras'.format(nome.find(' ')))
nome = nome.split()
print('Seu primeiro nome tem {} letras'.format(len(nome[0])))